options(install.packages.compile.from.source = "always")
install.packages(c('abind', 'acepack', 'acs', 'alphavantager') , repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('anytime', 'aplpack', 'arsenal', 'arules', 'arulesViz', 'askpass', 'assertthat'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('backports', 'base64enc', 'bayestestR', 'BH', 'BiasedUrn', 'bit', 'bit64'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('bitops', 'BlandAltmanLeh', 'blob', 'boot', 'broom', 'C50', 'callr', 'car'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('carData', 'caret', 'caTools', 'CDM', 'cellranger', 'checkmate', 'choroplethr'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('choroplethrMaps', 'Ckmeans.1d.dp', 'class', 'classInt', 'cli', 'clipr', 'cluster'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('cmprsk', 'codetools', 'coin', 'colorspace', 'combinat', 'compiler', 'corrplot'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('cowplot', 'cpp11', 'crayon', 'crosstalk', 'csvy', 'cubature', 'Cubist', 'curl'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('data.table', 'datarium', 'datasets', 'DBI', 'dbplyr', 'deepnet', 'dendextend'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('DEoptimR', 'Deriv', 'DescTools', 'digest', 'distr', 'dplyr', 'DT', 'dunn.test'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('e1071', 'earth', 'ellipsis', 'emmeans', 'EMT', 'epiR', 'epitools', 'eRm', 'estimability'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('evaluate', 'exactRankTests', 'expm', 'fansi', 'fAsianOptions', 'fastAdaboost'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('fastDummies', 'fBasics', 'feather', 'fOptions', 'forcats', 'foreach', 'forecast', 'Formula'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('fracdiff', 'fs', 'FSA', 'fst', 'furrr', 'future', 'gapminder', 'gbm', 'gbRd', 'gclus'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('gdata', 'generics', 'GGally', 'ggmap', 'ggplot2', 'ggpubr', 'ggraptR', 'ggrepel', 'ggsci'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('ggsignif', 'ggthemes', 'glmnet', 'globals', 'glue', 'gmodels', 'gower', 'GPArotation'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('gplots', 'graphics', 'gridExtra', 'gss', 'gtable', 'gtools', 'haven'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('hexbin', 'hexView', 'highr', 'Hmisc', 'hms', 'htmlTable', 'htmltools', 'htmlwidgets'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('httpuv', 'httr', 'igraph', 'insight', 'inum', 'iplots', 'ipred', 'irr', 'iterators'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('janitor', 'jpeg', 'jsonlite', 'kernlab', 'KernSmooth', 'klaR', 'km.ci', 'KMsurv', 'knitr'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('labeling', 'labelled', 'laeken', 'lars', 'later', 'lattice', 'latticeExtra', 'lazyeval'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('libcoin', 'lifecycle', 'limma', 'lme4', 'lmerTest', 'lmtest', 'logicFS', 'LogicReg', 'lpSolve'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('lubridate', 'magick', 'magrittr', 'manipulate', 'manipulateWidget', 'maptools', 'markdown'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('MASS', 'Matrix', 'MatrixModels', 'matrixStats', 'maxstat', 'mgcv', 'mime', 'miniUI'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('minqa', 'MKmisc', 'mnormt', 'modeldata', 'ModelMetrics', 'modelr', 'modeltools', 'moments'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('monomvn', 'multcomp', 'multcompView', 'munsell', 'mvtnorm', 'naniar', 'neuralnet'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('NeuralNetTools', 'nlme', 'nloptr', 'nnet', 'nortest', 'np', 'openssl', 'openxlsx', 'outliers'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('pacman', 'padr', 'palmerpenguins', 'pander', 'party', 'partykit', 'pbkrtest'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('performance', 'PerformanceAnalytics', 'pillar', 'pkgconfig', 'plogr', 'plotly', 'plotmo'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('plotrix', 'pls', 'plyr', 'png', 'polycor', 'polynom', 'PortfolioAnalytics', 'prettyunits'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('prob', 'pROC', 'processx', 'progress', 'promises', 'pryr', 'ps', 'pscl', 'psych', 'purrr'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('qap', 'qqplotr', 'quadprog', 'Quandl', 'quantmod', 'quantreg', 'questionr', 'R6'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('randomForest', 'ranger', 'rappdirs', 'rapportools', 'rbibutils', 'RcmdrMisc'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('RColorBrewer', 'rcompanion', 'Rcpp', 'RcppArmadillo', 'RcppEigen', 'RCurl', 'Rdpack'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('readODS', 'readr', 'readstata13', 'readxl', 'recipes', 'reghelper', 'registry', 'rel'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('rematch', 'remotes', 'reprex', 'reshape', 'reshape2', 'rgdal', 'rgl', 'Rglpk', 'RgoogleMaps'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('riingo', 'rio', 'rJava', 'RJDBC', 'rjson', 'RJSONIO', 'rlang', 'rmarkdown', 'rmatio', 'Rmisc'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('RMySQL', 'robustbase', 'ROCR', 'RODBCDBI', 'ROI', 'ROI.plugin.glpk', 'ROI.plugin.quadprog'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('rpart', 'rpart.plot', 'RPostgres', 'rsample', 'RSNNS', 'RSQLite', 'rstudioapi', 'rvest'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('sandwich', 'scales', 'scatterplot3d', 'sciplot', 'selectr', 'seriation', 'sf', 'sfsmisc'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('shape', 'shiny', 'simputation', 'slam', 'slider', 'snakecase', 'sourcetools', 'sp', 'SparseM'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('spatial', 'splitstackshape', 'stabledist', 'startupmsg'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('stringi', 'stringr', 'strucchange', 'summarytools', 'survival', 'survminer', 'survMisc'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('TAM', 'tcltk', 'TeachingDemos', 'TH.data', 'tibble', 'tidyquant', 'tidyr'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('tidyselect', 'tidyverse', 'tigris', 'timeDate', 'timeSeries', 'timetk', 'tinytex'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('tseries', 'TSP', 'units', 'UpSetR', 'urca', 'utf8'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('uuid', 'vcd', 'vctrs', 'VIM', 'viridis', 'viridisLite', 'visdat', 'visNetwork', 'visreg'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('warp', 'WDI', 'webshot', 'whisker', 'withr', 'WrightMap', 'xfun', 'xgboost', 'XML', 'xml2'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('xtable', 'xts', 'yaml', 'zeallot', 'zip', 'zoo', 'kableExtra', 'equatiomatic', 'foreign', 'textutils'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('formatR', 'devtools'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('texreg', 'ggbeeswarm', 'afex', 'effectsize', 'heplots'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('irrCAC', 'arrow', 'pzfx'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('DoE.base', 'FrF2', 'DoE.wrapper','effects'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('qcc', 'SixSigma'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('tzdb', 'vroom', 'farver','svglite', 'fastmap'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('r2mlm', 'ppcor'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('pwr', 'powerSurvEpi', 'presize'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('fitdistrplus', 'gamlss', 'gamlss.add', 'gamlss.dist'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('IAcsSPCR'), repos = 'http://cran.us.r-project.org', type = "both")
install.packages(c('generalhoslem'), repos = 'http://cran.us.r-project.org', type = "both")
# V18, logicFS