options(install.packages.compile.from.source = "always")
install.packages(c('abind', 'acepack', 'acs', 'alphavantager') )
install.packages(c('anytime', 'aplpack', 'arsenal', 'arules', 'arulesViz', 'askpass', 'assertthat'))
install.packages(c('backports', 'base64enc', 'bayestestR', 'BH', 'BiasedUrn', 'bit', 'bit64'))
install.packages(c('bitops', 'BlandAltmanLeh', 'blob', 'boot', 'broom', 'C50', 'callr', 'car'))
install.packages(c('carData', 'caret', 'caTools', 'CDM', 'cellranger', 'checkmate', 'choroplethr'))
install.packages(c('choroplethrMaps', 'Ckmeans.1d.dp', 'class', 'classInt', 'cli', 'clipr', 'cluster'))
install.packages(c('cmprsk', 'codetools', 'coin', 'colorspace', 'combinat', 'compiler', 'corrplot'))
install.packages(c('cowplot', 'cpp11', 'crayon', 'crosstalk', 'csvy', 'cubature', 'Cubist', 'curl'))
install.packages(c('data.table', 'datarium', 'datasets', 'DBI', 'dbplyr', 'deepnet', 'dendextend'))
install.packages(c('DEoptimR', 'Deriv', 'DescTools', 'digest', 'distr', 'dplyr', 'DT', 'dunn.test'))
install.packages(c('e1071', 'earth', 'ellipsis', 'emmeans', 'EMT', 'epiR', 'epitools', 'eRm', 'estimability'))
install.packages(c('evaluate', 'exactRankTests', 'expm', 'fansi', 'fAsianOptions', 'fastAdaboost'))
install.packages(c('fastDummies', 'fBasics', 'feather', 'fOptions', 'forcats', 'foreach', 'forecast', 'Formula'))
install.packages(c('fracdiff', 'fs', 'FSA', 'fst', 'furrr', 'future', 'gapminder', 'gbm', 'gbRd', 'gclus'))
install.packages(c('gdata', 'generics', 'GGally', 'ggmap', 'ggplot2', 'ggpubr', 'ggraptR', 'ggrepel', 'ggsci'))
install.packages(c('ggsignif', 'ggthemes', 'glmnet', 'globals', 'glue', 'gmodels', 'gower', 'GPArotation'))
install.packages(c('gplots', 'graphics', 'gridExtra', 'gss', 'gtable', 'gtools', 'haven'))
install.packages(c('hexbin', 'hexView', 'highr', 'Hmisc', 'hms', 'htmlTable', 'htmltools', 'htmlwidgets'))
install.packages(c('httpuv', 'httr', 'igraph', 'insight', 'inum', 'iplots', 'ipred', 'irr', 'iterators'))
install.packages(c('janitor', 'jpeg', 'jsonlite', 'kernlab', 'KernSmooth', 'klaR', 'km.ci', 'KMsurv', 'knitr'))
install.packages(c('labeling', 'labelled', 'laeken', 'lars', 'later', 'lattice', 'latticeExtra', 'lazyeval'))
install.packages(c('libcoin', 'lifecycle', 'limma', 'lme4', 'lmerTest', 'lmtest', 'logicFS', 'LogicReg', 'lpSolve'))
install.packages(c('lubridate', 'magick', 'magrittr', 'manipulate', 'manipulateWidget', 'maptools', 'markdown'))
install.packages(c('MASS', 'Matrix', 'MatrixModels', 'matrixStats', 'maxstat', 'mgcv', 'mime', 'miniUI'))
install.packages(c('minqa', 'MKmisc', 'mnormt', 'modeldata', 'ModelMetrics', 'modelr', 'modeltools', 'moments'))
install.packages(c('monomvn', 'multcomp', 'multcompView', 'munsell', 'mvtnorm', 'naniar', 'neuralnet'))
install.packages(c('NeuralNetTools', 'nlme', 'nloptr', 'nnet', 'nortest', 'np', 'openssl', 'openxlsx', 'outliers'))
install.packages(c('pacman', 'padr', 'palmerpenguins', 'pander', 'party', 'partykit', 'pbkrtest'))
install.packages(c('performance', 'PerformanceAnalytics', 'pillar', 'pkgconfig', 'plogr', 'plotly', 'plotmo'))
install.packages(c('plotrix', 'pls', 'plyr', 'png', 'polycor', 'polynom', 'PortfolioAnalytics', 'prettyunits'))
install.packages(c('prob', 'pROC', 'processx', 'progress', 'promises', 'pryr', 'ps', 'pscl', 'psych', 'purrr'))
install.packages(c('qap', 'qqplotr', 'quadprog', 'Quandl', 'quantmod', 'quantreg', 'questionr', 'R6'))
install.packages(c('randomForest', 'ranger', 'rappdirs', 'rapportools', 'rbibutils', 'RcmdrMisc'))
install.packages(c('RColorBrewer', 'rcompanion', 'Rcpp', 'RcppArmadillo', 'RcppEigen', 'RCurl', 'Rdpack'))
install.packages(c('readODS', 'readr', 'readstata13', 'readxl', 'recipes', 'reghelper', 'registry', 'rel'))
install.packages(c('rematch', 'remotes', 'reprex', 'reshape', 'reshape2', 'rgdal', 'rgl', 'Rglpk', 'RgoogleMaps'))
install.packages(c('riingo', 'rio', 'rJava', 'RJDBC', 'rjson', 'RJSONIO', 'rlang', 'rmarkdown', 'rmatio', 'Rmisc'))
install.packages(c('RMySQL', 'robustbase', 'ROCR', 'RODBCDBI', 'ROI', 'ROI.plugin.glpk', 'ROI.plugin.quadprog'))
install.packages(c('rpart', 'rpart.plot', 'RPostgres', 'rsample', 'RSNNS', 'RSQLite', 'rstudioapi', 'rvest'))
install.packages(c('sandwich', 'scales', 'scatterplot3d', 'sciplot', 'selectr', 'seriation', 'sf', 'sfsmisc'))
install.packages(c('shape', 'shiny', 'simputation', 'slam', 'slider', 'snakecase', 'sourcetools', 'sp', 'SparseM'))
install.packages(c('spatial', 'splitstackshape', 'stabledist', 'startupmsg'))
install.packages(c('stringi', 'stringr', 'strucchange', 'summarytools', 'survival', 'survminer', 'survMisc'))
install.packages(c('TAM', 'tcltk', 'TeachingDemos', 'TH.data', 'tibble', 'tidyquant', 'tidyr'))
install.packages(c('tidyselect', 'tidyverse', 'tigris', 'timeDate', 'timeSeries', 'timetk', 'tinytex'))
install.packages(c('tseries', 'TSP', 'units', 'UpSetR', 'urca', 'utf8'))
install.packages(c('uuid', 'vcd', 'vctrs', 'VIM', 'viridis', 'viridisLite', 'visdat', 'visNetwork', 'visreg'))
install.packages(c('warp', 'WDI', 'webshot', 'whisker', 'withr', 'WrightMap', 'xfun', 'xgboost', 'XML', 'xml2'))
install.packages(c('xtable', 'xts', 'yaml', 'zeallot', 'zip', 'zoo', 'kableExtra', 'equatiomatic', 'foreign', 'textutils'))
install.packages(c('formatR', 'devtools'))
install.packages(c('texreg', 'ggbeeswarm', 'afex', 'effectsize', 'heplots'))
install.packages(c('irrCAC', 'arrow', 'pzfx'))
install.packages(c('DoE.base', 'FrF2', 'DoE.wrapper','effects'))
install.packages(c('qcc', 'SixSigma'))
install.packages(c('tzdb', 'vroom', 'farver','svglite', 'fastmap'))
install.packages(c('r2mlm', 'ppcor'))
install.packages(c('pwr', 'powerSurvEpi', 'presize'))
install.packages(c('fitdistrplus', 'gamlss', 'gamlss.add', 'gamlss.dist'))
install.packages(c('IAcsSPCR'))
install.packages(c('generalhoslem'))
install.packages(c("arm", "conquer", "cubelyr", "diffobj", "fAsianOptions", "fOptions", "ggnetwork", "kutils", "leaps", "limma", "logicFS"))
install.packages(c("mi", "mlmRev", "network", "prob", "Rcmdr", "RcmdrPlugin.DoE", "rel", "relimp"))
install.packages(c("Runit", "sem", "sna", "statnet.common", "tcltk2", "TMB", "tmvnsim", "translations", "MatchIt"))
install.packages(c("drc", "fixest", "dreamerr", "stringmagic"))